### ISSUE TITLE
Customer/department doesn't make much sense

### ISSUE THREAD

**Issue by grechaw** [wpaven/gsd-workspaces#2]
We'd chatted about this last week, @wpaven - I'd done the exercise of pulling 'department' into a domain object but then it seems peculiar that customers have departments.

One option is to change department to something like 'segment'.  The existing values you 'load data' workspace would work ok for segment, even if the meaning of the model is a stretch.

Another would be to introduce another person into the model, a sales agent.  A sales agent could be a person who works for the company, and have a department and name and email, but not a billTo or shipTo.
This approach would complexify the model.  Let's work out in this issue what to do and change the workspaces.

**Comment by wpaven** [comment]
updated to segment.
